### ISSUE TITLE
Release branches are not created

### ISSUE THREAD

**Issue by matthiasbeyer** [cargo-bins/release-pr#74] opened 2022-12-01 11:20 UTC
I am not sure what I am doing wrong here: https://github.com/matthiasbeyer/test-cargo-release-pr-action/actions/runs/3583677179/jobs/6029394637

Thankfully I tried this on a testing repository :smile:

**Comment by passcod** [comment] 2022-12-01 11:32
The current version of the crate is 0.1.0 as per the Cargo.toml and you're trying to release 0.1.0, so it correctly does nothing.

**Comment by passcod** [comment] 2022-12-01 11:34
To release an initial version at 0.1.0, first set your versions manually to e.g. `0.0.0`.

**Comment by matthiasbeyer** [comment] 2022-12-01 11:41
Ah okay.
Is there a way to tell it to not increase the version string?

I would like to have that for workflow reasons...

**Comment by passcod** [comment] 2022-12-01 11:53
not currently, and it's also dubious github would allow creating a PR with empty commits, even if this action gained the ability to do that (you can't through the UI, for example).

mind explaining what your workflow would look like?

**Comment by passcod** [comment] 2022-12-01 20:31
Interesting! If you did want to use this action, then I think this small adaptation would get you there:

A "split off a release-M.N.x branch" workflow which:
- creates the `release-M.N.x` branch
  - pushes to it a commit that bumps the version to `M.N.0-pre` without publishing
- pushes a commit to `master` that bumps the version to `M.N+1.0-dev` without publishing

(This isn't something that this action will ever support, but you could fork it to do this if you want the frame of it.)

Then the "release prep" PR (with this action) should target the wanted release branch, always specify `patch` as the version argument to the action, and it will PR a commit bumping to the next available patch version. The first release on the branch will bump e.g. `0.1.0-pre` to `0.1.0`.

You'd then need a third workflow for the tagging and publishing, as usual. This action puts some machine-readable metadata in the PR body, so you can hook that workflow up to the merge event (another action that handles this flow is in the works, but not ready yet).

**Comment by passcod** [comment] 2022-12-21 13:34
Going to close this issue as it's not a bug.

**Closed by passcod** 2022-12-21 13:34 UTC
